# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Cmod-A7-Master.xdc

# Block Designs: bd/embedded_system/embedded_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system || ORIG_REF_NAME==embedded_system} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_microblaze_0_axi_periph_0/embedded_system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==embedded_system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_mdm_1_0/embedded_system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_mdm_1_0 || ORIG_REF_NAME==embedded_system_mdm_1_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_clk_wiz_1_0/embedded_system_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_clk_wiz_1_0 || ORIG_REF_NAME==embedded_system_clk_wiz_1_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_rst_clk_wiz_1_100M_0/embedded_system_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embedded_system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_axi_uartlite_0_0/embedded_system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_axi_uartlite_0_0 || ORIG_REF_NAME==embedded_system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_xadc_wiz_0_0/embedded_system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_xadc_wiz_0_0 || ORIG_REF_NAME==embedded_system_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_util_vector_logic_0_0/embedded_system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_util_vector_logic_0_0 || ORIG_REF_NAME==embedded_system_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_xbar_0/embedded_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_xbar_0 || ORIG_REF_NAME==embedded_system_xbar_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_microblaze_0_1/embedded_system_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_microblaze_0_1 || ORIG_REF_NAME==embedded_system_microblaze_0_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_dlmb_v10_1/embedded_system_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_dlmb_v10_1 || ORIG_REF_NAME==embedded_system_dlmb_v10_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_ilmb_v10_1/embedded_system_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_ilmb_v10_1 || ORIG_REF_NAME==embedded_system_ilmb_v10_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_dlmb_bram_if_cntlr_1/embedded_system_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==embedded_system_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_ilmb_bram_if_cntlr_1/embedded_system_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==embedded_system_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_lmb_bram_1/embedded_system_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_lmb_bram_1 || ORIG_REF_NAME==embedded_system_lmb_bram_1} -quiet] -quiet

# XDC: bd/embedded_system/embedded_system_ooc.xdc
