# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a15tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.cache/wt [current_project]
set_property parent.project_path C:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/hdl/embedded_system_wrapper.v
add_files C:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/embedded_system.bd
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_mdm_1_0/embedded_system_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_mdm_1_0/embedded_system_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_mdm_1_0/embedded_system_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_clk_wiz_1_0/embedded_system_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_clk_wiz_1_0/embedded_system_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_clk_wiz_1_0/embedded_system_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_rst_clk_wiz_1_100M_0/embedded_system_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_rst_clk_wiz_1_100M_0/embedded_system_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_rst_clk_wiz_1_100M_0/embedded_system_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_axi_uartlite_0_0/embedded_system_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_axi_uartlite_0_0/embedded_system_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_axi_uartlite_0_0/embedded_system_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_xadc_wiz_0_0/embedded_system_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_xadc_wiz_0_0/embedded_system_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_xbar_0/embedded_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_microblaze_0_1/embedded_system_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_microblaze_0_1/embedded_system_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_microblaze_0_1/embedded_system_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_dlmb_v10_1/embedded_system_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_dlmb_v10_1/embedded_system_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_ilmb_v10_1/embedded_system_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_ilmb_v10_1/embedded_system_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_dlmb_bram_if_cntlr_1/embedded_system_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_ilmb_bram_if_cntlr_1/embedded_system_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_lmb_bram_1/embedded_system_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/embedded_system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/constrs_1/new/Cmod-A7-Master.xdc
set_property used_in_implementation false [get_files C:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/constrs_1/new/Cmod-A7-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top embedded_system_wrapper -part xc7a15tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef embedded_system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file embedded_system_wrapper_utilization_synth.rpt -pb embedded_system_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
