# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_lmb_bram_1/embedded_system_lmb_bram_1.xci
# IP: The module: 'embedded_system_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_lmb_bram_1/embedded_system_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embedded_system_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_lmb_bram_1/embedded_system_lmb_bram_1.xci
# IP: The module: 'embedded_system_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/miet/mag_sem_3/embedded_systems/lab_1/lab_1.srcs/sources_1/bd/embedded_system/ip/embedded_system_lmb_bram_1/embedded_system_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embedded_system_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
